version: '3'

services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - "3306"
#    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=httprunner


  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./static:/django_static
    ports:
      - "80:80"
    depends_on:
      - web


  web:
    build: .
    working_dir: /HttpRunnerManager
    volumes:
      - .:/HttpRunnerManager
    command: uwsgi --ini ./uwsgi.ini
    expose:
      - "8001"
    depends_on:
      - mysql
    environment:
       MYSQL_CONTAINER_NAME: mysql
       MYSQL_PORT: 3306
       MYSQL_USER: root
       MYSQL_PASSWORD: 123456
       MYSQL_DATABASE: httprunner


